name: ShambhalaTattoos
favicon: null
layout_spectrum: 0.33790357899852097
typography_spectrum: 0.3362791845574975
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.8142846070695668
  lightness: 0.24983085505664349
  saturation: 0.1311509027145803
  rhythmicContrast: 0.5606838217936456
purpose: []
